name: Render docs

on:
  push:
    branches:
      - default

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Generate docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps
      - name: Stick a CNAME in there
        run: echo renee.kooi.me > target/doc/CNAME
      - name: Publish site
        if: success()
        uses: dswistowski/surge-sh-action
        with:
          domain: yolofd.surge.sh
          project: target/doc
          login: ${{secrets.SURGE_LOGIN}}
          token: ${{secrets.SURGE_TOKEN}}
